# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("出题神器")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(250, 10, 351, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.button_gen = QtWidgets.QPushButton(self.centralwidget)
        self.button_gen.setGeometry(QtCore.QRect(330, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.button_gen.setFont(font)
        self.button_gen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_gen.setObjectName("button_gen")
        self.ck_add_minus = QtWidgets.QCheckBox(self.centralwidget)
        self.ck_add_minus.setGeometry(QtCore.QRect(240, 130, 121, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.ck_add_minus.setFont(font)
        self.ck_add_minus.setObjectName("ck_add_minus")
        self.ck_multi_plus = QtWidgets.QCheckBox(self.centralwidget)
        self.ck_multi_plus.setGeometry(QtCore.QRect(240, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.ck_multi_plus.setFont(font)
        self.ck_multi_plus.setObjectName("ck_multi_plus")
        self.title_1 = QtWidgets.QLabel(self.centralwidget)
        self.title_1.setGeometry(QtCore.QRect(190, 90, 471, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.title_1.setFont(font)
        self.title_1.setObjectName("title_1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 230, 501, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 330, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.spinBox_multi = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_multi.setGeometry(QtCore.QRect(330, 330, 71, 31))
        self.spinBox_multi.setObjectName("spinBox_multi")
        self.spinBox_add = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_add.setGeometry(QtCore.QRect(330, 280, 71, 31))
        self.spinBox_add.setObjectName("spinBox_add")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "加减乘除出题神器"))
        self.button_gen.setText(_translate("MainWindow", "生成题目"))
        self.ck_add_minus.setText(_translate("MainWindow", "加减法"))
        self.ck_multi_plus.setText(_translate("MainWindow", "乘除法"))
        self.title_1.setText(_translate("MainWindow", "1、请选择出题范围，在前面打勾即可"))
        self.label_3.setText(_translate("MainWindow", "2、请选择出题难度，选择一个数字"))
        self.label_4.setText(_translate("MainWindow", "加减法"))
        self.label_5.setText(_translate("MainWindow", " 乘除法"))




